### ISSUE TITLE
[react] Bug with <div className="">

### ISSUE THREAD

**Issue by Yamakaky** [babel/babel-eslint#216]
Previously: https://github.com/yannickcr/eslint-plugin-react/issues/335 https://github.com/eslint/eslint/issues/4568
The following file issues an error.

test.js:
```
<div className=""></div>
```

error:
```
/tmp/test/node_modules/eslint/lib/rules/no-irregular-whitespace.js:51
            if (node.raw.match(irregularWhitespace) || node.raw.match(irregularLineTerminators)) {
                        ^

TypeError: Cannot read property "match" of null
    at EventEmitter.removeInvalidNodeErrors (/tmp/test/node_modules/eslint/lib/rules/no-irregular-whitespace.js:51:25)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/tmp/test/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/tmp/test/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/tmp/test/node_modules/eslint/lib/eslint.js:767:36)
    at Controller.__execute (/tmp/test/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/tmp/test/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/tmp/test/node_modules/eslint/lib/eslint.js:764:24)
    at processText (/tmp/test/node_modules/eslint/lib/cli-engine.js:230:27)

```

installed packages: babel babel-eslint eslint eslint-plugin-react

eslintrc:
```
parser: babel-eslint
rules:
  indent:
    - 2
    - 4
  quotes:
    - 2
    - double
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
```
